# Generated by Django 3.2.8 on 2021-11-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=4)),
                ('lesson_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('deadline', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupstudents')),
                ('subgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_name', models.CharField(max_length=1000)),
                ('rating_value', models.IntegerField()),
                ('comment', models.CharField(max_length=5000)),
                ('team_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_name', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
