# Generated by Django 3.2.8 on 2021-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
