# Generated by Django 3.2.8 on 2021-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_group_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
