# Generated by Django 3.2.8 on 2021-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211210_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
